### PR TITLE
Trackmate

### PR DESCRIPTION
**Pull request by jburel**
In this Jython script we analyse all the images in a project using Trackmate
* The Tracks are saved as ROI, each spot is saved as an Ellipse (z and t set), the track itself as polyline  (no z/t set). The shapes are linked to the ROI
* The track and spot measurements are saved in an OMERO table. The table is then linked to the Project
* A summary table i.e. a row per image is also created. It contains track average velocity, spot average quality. This table is also linked to the project so it can be used in parade

* Tracks and spots can be viewed in iviewer and parade

cc @pwalczysko @will-moore @jrswedlow

### CODE REVIEW

**Comment by pwalczysko** [comment]
I have used this script on my localhost and was able to repeat exactly what  you were showing to me.
This means: Parade has problems, but the tracks on the second image make sense. Strange that the ellipse ROIs do not follow any particular spots, but the mitotic event is captured well in the right-hand track in the image, I think we could show this.

Did not find any problems with the running of the script.

Ready to merge FMPOV

**Comment by pwalczysko** [comment]
Interestingly, I did not have to create a Projection out of the images before I started Trackmate... It still worked

**Comment by pwalczysko** [comment]
Do we want to produce a CSV too as the table -> Parade does not work for the moment ?

**Comment by jburel** [comment]
Parade won't work. I discussed with @will-moore. This will require some investigation
That's what we don't want to show it for that dataset
We can certainly create a CSV too.

**Comment by jburel** [comment]
@pwalczysko summary CSV now attached to project too

**Comment by pwalczysko** [comment]
This works nicely, I went through the workflow and updated the screenshot in the walkthrough.

Some RFEs Re the CSV:

1.  Image ID is not well formatted

screen shot 2018-08-23 at 19 29 25


2. Velocity could be in microns per minute, not pixel per frame (not sure if this is possbile - do you have the calibration data available in Fiji ? (the image is timestampted and calibrated in OMERO)

But I do not think these are blockers, we could show the workflow as it is.

**Comment by pwalczysko** [comment]
The image ID in CSV is now as expected.

The CSV itself is strangely named, some ``xxXs`` is inside the name, but I guess this is quite minor.

Happy to merge FMPOV

**Comment by jburel** [comment]
It is due to the fact that we use a tmp file
I will change it

**Comment by jburel** [comment]
@pwalczysko name updated

**Comment by pwalczysko** [comment]
The name is fine. The whole workflow still works.

Sorry, I am just finding those things too late, I found another one

In the CSV, there are two columns (the right-most ones) which have no description ? Maybe if the description cannot be passed, then better do not put the two column numbers in at all.

screen shot 2018-08-25 at 18 33 29

**Comment by jburel** [comment]
@pwalczysko well spotted I was not using the correct table
This should now be fixed

**Comment by pwalczysko** [comment]
Yes, I understand now. Now, no two values are the same for the two analysed images (which makes more sense). The non-described columns are gone as well.
Checked the average speed, and I think the values make sense 

Ready to merge FMPOV

**Pull request merged**
