### PR TITLE
Add "white" attribute

### PR DESCRIPTION
**Pull request by jburel**
Problem noticed by @pwalczysko after upgrading Fiji
See 
https://trello.com/c/mkF1wTda/18-fix-analysis-workflow

### CODE REVIEW

**Comment by pwalczysko** [comment]
https://github.com/ome/training-scripts/pull/46/commits/9da302a7979172b529631355787762232429b27d#diff-d30ffcd2aaee25ccb44c198d6cc98e15 works

**Comment by pwalczysko** [comment]
https://github.com/ome/training-scripts/blob/9da302a7979172b529631355787762232429b27d/practical/groovy/analyse_dataset_save_rois_and_summary_table.groovy works too

**Comment by pwalczysko** [comment]
https://github.com/ome/training-scripts/blob/9da302a7979172b529631355787762232429b27d/practical/groovy/analyse_particles_for_another_user.groovy works as well

**Comment by pwalczysko** [comment]
```
Started New_.groovy at Wed Nov 07 10:59:22 GMT 2018
java.lang.ArrayIndexOutOfBoundsException: 26
	at org.codehaus.groovy.runtime.dgmimpl.arrays.ObjectArrayGetAtMetaMethod$MyPojoMetaMethodSite.call(ObjectArrayGetAtMetaMethod.java:60)
	at Script1.save_summary_as_omero_table(Script1.groovy:365)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:151)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine$2.invokeMethod(GroovyScriptEngine.java:283)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190)
	at Script1.run(Script1.groovy:508)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.eval(GroovyScriptEngine.java:303)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.eval(GroovyScriptEngine.java:122)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

After quite a while of the running of https://github.com/ome/training-scripts/blob/9da302a7979172b529631355787762232429b27d/practical/groovy/idr0021.groovy I get the above error. The ROIs created by the script are fine, I guess this is a bit mysterious crash, @jburel ?

**Comment by pwalczysko** [comment]
```
Traceback (most recent call last):
  File "New_.py", line 207, in <module>
  File "New_.py", line 101, in get_image_ids
  File "New_.py", line 121, in switch_security_context
Cannot load the required group.
	at omero.gateway.facility.Facility.handleException(Facility.java:305)
	at omero.gateway.facility.AdminFacility.lookupExperimenter(AdminFacility.java:306)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
omero.gateway.exception.DSAccessException: omero.gateway.exception.DSAccessException: Cannot access data. 
Cannot load the required group.

	at org.python.core.Py.JavaError(Py.java:552)
	at org.python.core.Py.JavaError(Py.java:543)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:515)
	at org.python.core.PyObject.__call__(PyObject.java:519)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at org.python.pycode._pyx3.switch_security_context$3(New_.py:124)
	at org.python.pycode._pyx3.call_function(New_.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:154)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at org.python.pycode._pyx3.get_image_ids$2(New_.py:113)
	at org.python.pycode._pyx3.call_function(New_.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:171)
	at org.python.core.PyFunction.__call__(PyFunction.java:434)
	at org.python.pycode._pyx3.f$0(New_.py:241)
	at org.python.pycode._pyx3.call_function(New_.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: omero.gateway.exception.DSAccessException: Cannot access data. 
Cannot load the required group.
	at omero.gateway.facility.Facility.handleException(Facility.java:305)
	at omero.gateway.facility.AdminFacility.lookupExperimenter(AdminFacility.java:306)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)
	... 34 more
Caused by: omero.gateway.exception.DSOutOfServiceException: Failed to create connector
	at omero.gateway.Gateway.createConnector(Gateway.java:1665)
	at omero.gateway.Gateway.getConnector(Gateway.java:1535)
	at omero.gateway.Gateway.getAdminService(Gateway.java:902)
	at omero.gateway.facility.AdminFacility.lookupExperimenter(AdminFacility.java:300)
	... 39 more
Caused by: java.lang.IllegalArgumentException: must set security context with a valid group ID
	at omero.gateway.Gateway.createConnector(Gateway.java:1655)
	... 42 more
```

When running https://github.com/ome/training-scripts/blob/9da302a7979172b529631355787762232429b27d/practical/jython/analyse_particles_for_another_user.jy - this crash comes very quickly, and repeats for me.

**Comment by jburel** [comment]
Strange, looks like a value is not correctly picked when creating the table

**Comment by pwalczysko** [comment]
```
Started New_.py at Wed Nov 07 11:46:43 GMT 2018
Traceback (most recent call last):
  File "New_.py", line 184, in <module>
  File "New_.py", line 123, in open_omero_image
	at java.lang.System.arraycopy(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
java.lang.ArrayStoreException: java.lang.ArrayStoreException

	at org.python.core.Py.JavaError(Py.java:552)
	at org.python.core.Py.JavaError(Py.java:543)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:450)
	at org.python.core.PyObject.__call__(PyObject.java:454)
	at org.python.pycode._pyx3.open_omero_image$2(New_.py:138)
	at org.python.pycode._pyx3.call_function(New_.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:154)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at org.python.pycode._pyx3.f$0(New_.py:204)
	at org.python.pycode._pyx3.call_function(New_.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayStoreException
	at java.lang.System.arraycopy(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)
	... 28 more
```

After running https://github.com/ome/training-scripts/blob/9da302a7979172b529631355787762232429b27d/practical/jython/analyse_particles_from_dataset.jy - note that if there are no "Mitosis" tags on the images, the script works fine. Once I added Mitosis tag on 2 images, this crash happened quickly and repeatably.

**Comment by jburel** [comment]
We need to review the Jython script something does not seem correct.
It is not related to the change i.e. adding the "white" attribute

**Comment by pwalczysko** [comment]
```
Started New_.py at Wed Nov 07 11:51:57 GMT 2018
Traceback (most recent call last):
  File "New_.py", line 445, in <module>
  File "New_.py", line 309, in save_summary_as_omero_table
IndexError: index out of range: 17

	at org.python.core.Py.IndexError(Py.java:280)
	at org.python.core.SequenceIndexDelegate.checkIdxAndGetItem(SequenceIndexDelegate.java:63)
	at org.python.core.PySequence.seq___getitem__(PySequence.java:377)
	at org.python.core.PySequence.__getitem__(PySequence.java:373)
	at org.python.pycode._pyx0.save_summary_as_omero_table$10(New_.py:320)
	at org.python.pycode._pyx0.call_function(New_.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:189)
	at org.python.core.PyFunction.__call__(PyFunction.java:446)
	at org.python.pycode._pyx0.f$0(New_.py:452)
	at org.python.pycode._pyx0.call_function(New_.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
 
got this one after running https://github.com/ome/training-scripts/blob/9da302a7979172b529631355787762232429b27d/practical/jython/idr0021.jy

**Comment by pwalczysko** [comment]
The ROI drawing in all the script is okay now.

Some of the scripts do not work for other reasons.

Ready to merge.

**Comment by jburel** [comment]
I will look at the failed scripts in another PR. Could you create a card and add it to the Turku board so I do not forget

**Comment by pwalczysko** [comment]
done https://trello.com/c/LurS2xja/20-fiji-scripts-fix

**Pull request merged**
