### PR TITLE
create_groups_users (for ELMI)

### PR DESCRIPTION
**Pull request by pwalczysko**
This is a script adjusted from https://github.com/openmicroscopy/management_tools/blob/master/ci/config/create_users and it works fine on tadpole.

Definitely some room for parametrization is there. 

``bin/omero load create_groups_users``

### CODE REVIEW

**Comment by jburel** [comment]
@pwalczysko could you test the latest commits?

**Comment by pwalczysko** [comment]
The script works fine if on empty db.

When a user or a group with that name already exists, the script stops.
I thought that in that case, the script would still do the rest of the users then (for example, user-4 exists, the script correctly does user-1, 2, 3, then reports that user-4 exists and stops, I would prefer if the script continues with user-5, 6, 7...)
But I can see this might be too much to want.

**Comment by joshmoore** [comment]
I think `--ignore-existing` is missing.

**Comment by pwalczysko** [comment]
This https://github.com/ome/training-scripts/pull/19/commits/a34fd74ae331eea8bd5d77e5029408734c69a83d works, thank you @joshmoore

**Comment by jburel** [comment]
@pwalczysko Tested your last commit everything works nicely
Merging

**Pull request merged**
