### PR TITLE
New copy_tags_ratings.py script

### PR DESCRIPTION
**Pull request by will-moore**
New script for replicating the Tags and Ratings from trainer-1's dataset to all other users.

Usage:
```
$ python maintenance/scripts/copy_tags_ratings.py siRNAi-HeLa password
```
cc @pwalczysko

### CODE REVIEW

**Comment by will-moore** [comment]
I've run this script for all users on outreach.

**Comment by pwalczysko** [comment]
The results are as expected. Ready to merge FMPOV

**Comment by will-moore** [comment]
From discussion at https://github.com/ome/training-scripts/commit/9a31c2f9955ad88ce4941e1278e09ea094764a5b#r29612487 I added ```delete=True``` to the ```delete_annotations.py``` and ```delete_ROIs.py``` scripts. I think this helps.

**Comment by pwalczysko** [comment]
Tested both scripts adjusted in https://github.com/ome/training-scripts/pull/23/commits/0bbbd6d3978ccf997f7aca27a6814b59bb946f5a - now they work as expected, all the ROIs and KVPs are deleted on all images.

Ready to merge.

**Pull request merged**
