### PR TITLE
idr21

### PR DESCRIPTION
**Pull request by jburel**
Use columns length instead of row.size()

I have not been able to reproduce the issue.
This could be the cause of the intermittent issue reported by @pwalczysko 

see https://github.com/ome/training-scripts/pull/46#issuecomment-436622875

### CODE REVIEW

**Comment by jburel** [comment]
I am using user-3 on eel (idr21 dataset)

**Comment by pwalczysko** [comment]
```Started New_.groovy at Mon Nov 12 17:59:55 GMT 2018
omero.gateway.exception.DSAccessException: Cannot access data. 
Could not add table
	at omero.gateway.facility.Facility.handleException(Facility.java:305)
	at omero.gateway.facility.TablesFacility.addTable(TablesFacility.java:134)
	at omero.gateway.facility.TablesFacility$addTable.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:149)
	at Script1.save_summary_as_omero_table(Script1.groovy:373)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:151)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine$2.invokeMethod(GroovyScriptEngine.java:283)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190)
	at Script1.run(Script1.groovy:507)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.eval(GroovyScriptEngine.java:303)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.eval(GroovyScriptEngine.java:122)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to omero.gateway.model.ImageData
	at omero.gateway.facility.TablesFacilityHelper.createColumn(TablesFacilityHelper.java:342)
	at omero.gateway.facility.TablesFacilityHelper.parseTableData(TablesFacilityHelper.java:109)
	at omero.gateway.facility.TablesFacility.addTable(TablesFacility.java:102)
	... 32 more
```

**Comment by pwalczysko** [comment]
But with ``user-3`` on eel

```
creating summary results for image ID 118752
Found index: 1
creating summary results for image ID 118776
processing done
```
success.

**Comment by pwalczysko** [comment]
Again, success with user-3 on eel, but crash on user-1 on outreach

```
Started New_.groovy at Tue Nov 13 10:58:44 GMT 2018
java.lang.NullPointerException
	at org.openmicroscopy.shoola.util.roi.io.ROIReader.formatShape(ROIReader.java:233)
	at org.openmicroscopy.shoola.util.roi.io.ROIReader.convertPolygon(ROIReader.java:182)
	at org.openmicroscopy.shoola.util.roi.io.ROIReader.read(ROIReader.java:338)
```

**Comment by pwalczysko** [comment]
Repeat, as user-1 on outreach

```
omero.gateway.exception.DSAccessException: Cannot access data. 
Could not add table
	at omero.gateway.facility.Facility.handleException(Facility.java:305)
	at omero.gateway.facility.TablesFacility.addTable(TablesFacility.java:134)
	at omero.gateway.facility.TablesFacility$addTable.call(Unknown Source)
```

**Comment by jburel** [comment]
cf. https://github.com/ome/training-scripts/pull/49#issuecomment-438225245 
I have opened a PR, I did not see it happening see https://github.com/openmicroscopy/openmicroscopy/pull/5905

**Comment by pwalczysko** [comment]
The groovy script here worked fine when used together with https://github.com/openmicroscopy/openmicroscopy/pull/5905

**Comment by pwalczysko** [comment]
The jython script was a success too with analogous setup as https://github.com/ome/training-scripts/pull/49#issuecomment-438688717.

Ready to merge FMPOV

**Pull request merged**
