### PR TITLE
Add commands for omero-downloader

### PR DESCRIPTION
**Pull request by pwalczysko**
In prep of the Oxford workshop, adding a textfile for easy of Copy&Paste of the commands for the downloader section of the workflow.
Search for "Image export using omero-downloade" in https://downloads.openmicroscopy.org/presentations/2019/Dundee-April/Dundee_April_2019_Day1.pdf to see the whole workflow.

cc @dominikl @mtbc @jburel

### CODE REVIEW

**Comment by pwalczysko** [comment]
Now it works fine for me when copied from the raw file.

**Comment by mtbc** [comment]
Sorry you have to do this at all @pwalczysko! I wish I knew of some XSLT-like thing that would make it easy to remove the zero-width characters from the PDFs.

**Comment by dominikl** [comment]
👍 Works, good to merge.

**Comment by pwalczysko** [comment]
Merge then ?
We need the link to this in the walkthrough pdf for Oxford

**Comment by jburel** [comment]
We need to tag the repo before adding links to the PDFs

**Pull request merged**
